MarketCenterConfig:
  ServerIP: 127.0.0.1
  Port: 8001
  ExchangeID: CFFEX
  BusinessType: 3
  ToMonitor: true
  Future: true
  TotalTick: 172800
  MarketServer: MarketServer
  RecvTimeOut: 60000
  CPUSET: -1, -1, -1
  CallAuctionPeriod: 00:00:00.000
  ContinuousAuctionPeriod:
    - 00:00:00.000-06:00:00.000
    - 06:00:00.000-12:00:00.000
    - 12:00:00.000-18:00:00.000
    - 18:00:00.000-23:59:59.999
  TickerListPath: /root/projects/quantfabric-study/QuantFabric/runtime/config/TickerList.yml
  APIConfig: /root/projects/quantfabric-study/QuantFabric/runtime/config/XMarketCenter.yml
