MarketCenterConfig:
  ServerIP: 127.0.0.1
  Port: 8001
  ExchangeID: SZSE
  BusinessType: 1
  ToMonitor: true
  Future: false
  TotalTick: 14400
  MarketServer: MarketServer
  RecvTimeOut: 60000
  CPUSET: -1, -1, -1
  CallAuctionPeriod: 00:00:00.000
  ContinuousAuctionPeriod:
    - 00:00:00.000-23:59:59.999
  TickerListPath: /root/projects/quantfabric-study/QuantFabric/runtime/config/TickerListStock.yml
  APIConfig: /root/projects/quantfabric-study/QuantFabric/runtime/config/XMarketCenterPyTdx.yml
PyTdxBridgeConfig:
  Host: 127.0.0.1
  Port: 19001
