XQuantConfig:
  XWatcherIP: 127.0.0.1
  XWatcherPort: 8001
  StrategyName: StockReadOnlyStrategy
  AccountList: 610000071840
  TickerListPath: /root/projects/quantfabric-study/QuantFabric/runtime/config/TickerListStock.yml
  MarketServerName: MarketServer
  OrderServerName: OrderServer
  CPUSET: -1
  SnapshotInterval: 0
  SlicePerSec: 1
  KLineIntervals: 60, 300
  TradingSection:
    - 00:00:00-23:59:59
