XQuantConfig:
  XWatcherIP: 127.0.0.1
  XWatcherPort: 8001
  StrategyName: TestStrategy
  AccountList: 188795
  TickerListPath: /root/projects/quantfabric-study/QuantFabric/runtime/config/TickerList.yml
  MarketServerName: MarketServer
  OrderServerName: OrderServer
  CPUSET: -1
  SnapshotInterval: 0
  SlicePerSec: 2
  KLineIntervals: 60, 300
  TradingSection:
    - 00:00:00-23:59:59
