XTraderConfig:
  Product: ATPTest
  Broker: Guosen
  BrokerID: 6100
  Account: 610000071840
  Password: qQ56m+dZOESs024m5vhmVw==
  BusinessType: 1
  CloseToday: false
  AppID: quantfabric_atp_bridge
  AuthCode: test
  ServerIP: 127.0.0.1
  Port: 8001
  OpenTime: 00:00:00.000
  CloseTime: 23:59:59.999
  QryFund: true
  CancelAll: false
  CPUSET: -1, -1
  TickerListPath: /root/projects/quantfabric-study/QuantFabric/runtime/config/TickerListStock.yml
  ErrorPath: /root/projects/quantfabric-study/QuantFabric/XTrader/Config/CTPError.yml
  RiskServerName: RiskServer
  OrderServerName: OrderServer
  TraderAPI: ATP
  TraderAPIConfig: /root/projects/quantfabric-study/QuantFabric/runtime/config/XTraderATP.yml
ATPBridgeConfig:
  Host: 127.0.0.1
  Port: 19002
  EnableOrders: false
